In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
data = pd.read_csv('../data(05_22).csv', index_col=False)

C:\Users\smhrd\AppData\Local\Temp\ipykernel_24140\2263673705.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('../data(05_22).csv', index_col=False)

count    58062.000000
mean       130.525576
std         28.309181
min         13.000000
25%        111.000000
50%        131.000000
75%        151.000000
max        209.000000
Name: eBoxMeanB, dtype: float64

In [95]:
ones =data[data.loc[:,'Shape_num']==7]

In [102]:
ones[ones['label']=='glass'].describe()

,Shape_num,point1_x,point1_y,point2_x,point2_y,AllPixelMeanR,AllPixelMeanG,AllPixelMeanB,bBoxMeanR,bBoxMeanG,bBoxMeanB,eBoxMeanR,eBoxMeanG,eBoxMeanB
count,32.0,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.00000
mean,6.0,1073.214039,1273.634339,1604.048148,1793.381157,142.750000,134.312500,124.312500,141.093750,133.312500,119.531250,139.562500,131.312500,121.65625
std,0.0,650.929895,667.527527,649.663404,744.674251,24.581661,26.797253,30.432832,34.838206,31.919695,39.966102,23.571357,25.911061,29.48002
min,6.0,194.000000,125.434978,753.005464,673.529412,91.000000,90.000000,85.000000,74.000000,82.000000,66.000000,91.000000,90.000000,83.00000
25%,6.0,518.238011,845.412818,1053.675406,1372.570269,132.750000,115.000000,98.750000,124.250000,97.750000,84.000000,130.000000,113.000000,97.50000
50%,6.0,978.075170,1062.143777,1455.801109,1618.943028,143.000000,133.500000,123.500000,154.000000,136.000000,110.000000,139.500000,130.500000,122.00000
75%,6.0,1450.062125,1654.536593,1963.087629,2194.288256,161.000000,154.000000,145.000000,166.250000,158.500000,154.000000,152.500000,146.000000,138.00000
max,6.0,2299.498387,2924.390244,2988.423529,3786.746396,185.000000,182.000000,178.000000,190.000000,190.000000,190.000000,182.000000,179.000000,175.00000