### 목표
- 객체가 한 개인 플라스틱 이미지의 배경에 대한 픽셀의 평균을 구하여 분포도를 확인하자

In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import cv2

In [8]:
data = pd.read_csv('../data(json).csv', index_col=False)
data

,imagePath,label,Shape_num,width,height,point1_x,point1_y,point2_x,point2_y
0,3403540,pack,1,2272,4032,926,1682,1248,2284
1,3403580,pack,2,2272,4032,920,1544,1462,1969
2,3403580,pack,2,2272,4032,892,1890,1317,2448
3,3403658,can,1,2272,4032,999,1701,1295,2224
4,3403788,glass,1,4032,2272,1435,972,2672,1185
...,...,...,...,...,...,...,...,...,...
58057,t3_0029,can,6,1920,1080,721,375,967,665
58058,t3_0029,pack,6,1920,1080,591,356,831,573
58059,t3_0029,glass,6,1920,1080,451,508,869,767
58060,t3_0030,pet,2,1920,1080,706,555,859,949
58061,t3_0030,pet,2,1920,1080,855,216,1224,450

In [9]:
data[data['Shape_num']==1]

,imagePath,label,Shape_num,width,height,point1_x,point1_y,point2_x,point2_y
0,3403540,pack,1,2272,4032,926,1682,1248,2284
3,3403658,can,1,2272,4032,999,1701,1295,2224
4,3403788,glass,1,4032,2272,1435,972,2672,1185
5,3403841,paper,1,2268,4032,860,1663,1515,2419
6,3403871,paper,1,2268,4032,861,1683,1493,2445
...,...,...,...,...,...,...,...,...,...
57685,custom_00227,vinyl,1,4032,2268,1312,421,2198,1569
57690,custom_00230,vinyl,1,2268,4032,700,1559,1639,2543
57858,custom_00285,glass,1,2268,4032,630,2882,1380,3243
57861,custom_00287,glass,1,2268,4032,621,2878,1372,3240
57920,custom_00307,glass,1,2268,4032,497,1310,1284,2371

In [10]:
data['width'].value_counts()

2268    29804
2250     3098
2592     2623
2322     2618
1836     2498
4032     2489
1440     2320
2272     1606
4128     1426
2252     1361
2988     1036
3184      846
2560      814
2160      776
1602      599
2340      517
2620      459
4608      448
4000      389
2604      290
3840      275
2336      251
4160      183
3264      177
4640      176
1920      134
2610      133
4624      117
1152      103
5664       94
2848       91
5312       77
1080       69
4656       41
2612       38
1840       33
2248       19
3968       15
2240        9
5504        5
3096        2
3024        2
1312        1
Name: width, dtype: int64